apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ii4t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ii4t
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ii4t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ii4t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ii4t
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gymq-tenant/rhtap-demo-app/hacbs-test-project-ii4t@sha256:4bd1a629b2b9332d8c220fe86d41167b66c5dda97da54cdc1a309ff81c5b014a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
