apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ii4t
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gymq-tenant/rhtap-demo-app/hacbs-test-project-ii4t@sha256:db9d9c26c8257708e24d43a1fefba19412dab3d3e76d3baabbbeeb244a561f5a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
